### ISSUE TITLE
trouble compiling on Raspbian

### ISSUE THREAD

**Issue by archenemies** [rosmanov/bee-host#1]
I couldn't get [Textern](https://github.com/jlebon/textern) to work, so I'm trying your project as a substitute.

I'm trying to compile this on a Raspbian (ARM) system, and getting errors. Is there a reason why the various compilation options are tied to particular architecture?

    $ ./build.sh
    Processing ./CMake/Toolchain-Linux-amd64.cmake
    Using toolchain ./CMake/Toolchain-Linux-amd64.cmake in 'Debug' mode
    -- The C compiler identification is GNU 8.3.0
    -- Check for working C compiler: /usr/bin/gcc
    -- Check for working C compiler: /usr/bin/gcc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Performing Test HAVE___BUILTIN_EXPECT
    -- Performing Test HAVE___BUILTIN_EXPECT - Success
    -- Looking for strndup
    -- Looking for strndup - found
    -- Configuring done
    CMake Error at CMakeLists.txt:53 (add_executable):
      Cannot find source file:

        /home/me/bee-host/external/cJSON/src/cjson/cJSON.c

      Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
      .hpp .hxx .in .txx

    CMake Error at CMakeLists.txt:53 (add_executable):
      No SOURCES given to target: beectl

    CMake Error at CMakeLists.txt:65 (add_executable):
      No SOURCES given to target: json-patch

    -- Build files have been written to: /home/me/bee-host
    make: *** No targets specified and no makefile found.  Stop.
    make: *** No rule to make target 'package'.  Stop.
    Processing ./CMake/Toolchain-Linux-i386.cmake
    Using toolchain ./CMake/Toolchain-Linux-i386.cmake in 'Debug' mode
    -- The C compiler identification is unknown
    -- Check for working C compiler: /usr/bin/gcc
    -- Check for working C compiler: /usr/bin/gcc -- broken
    CMake Error at /usr/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:52 (message):
      The C compiler

        "/usr/bin/gcc"

      is not able to compile a simple test program.

      It fails with the following output:

        Change Dir: /home/me/bee-host/CMakeFiles/CMakeTmp

        Run Build Command:"/usr/bin/make" "cmTC_df251/fast"
        /usr/bin/make -f CMakeFiles/cmTC_df251.dir/build.make CMakeFiles/cmTC_df251.dir/build
        make[1]: Entering directory '/home/me/bee-host/CMakeFiles/CMakeTmp'
        Building C object CMakeFiles/cmTC_df251.dir/testCCompiler.c.o
        /usr/bin/gcc -m32    -o CMakeFiles/cmTC_df251.dir/testCCompiler.c.o   -c /home/me/bee-host/CMakeFiles/CMakeTmp/testCCompiler.c
        gcc: error: unrecognized command line option ‘-m32’; did you mean ‘-mbe32’?
        make[1]: *** [CMakeFiles/cmTC_df251.dir/build.make:66: CMakeFiles/cmTC_df251.dir/testCCompiler.c.o] Error 1
        make[1]: Leaving directory '/home/me/bee-host/CMakeFiles/CMakeTmp'
        make: *** [Makefile:121: cmTC_df251/fast] Error 2

      CMake will not be able to correctly generate this project.
    Call Stack (most recent call first):
      CMakeLists.txt:8 (project)

    -- Configuring incomplete, errors occurred!
    See also "/home/me/bee-host/CMakeFiles/CMakeOutput.log".
    See also "/home/me/bee-host/CMakeFiles/CMakeError.log".
    make: *** No targets specified and no makefile found.  Stop.
    make: *** No rule to make target 'package'.  Stop.
    Processing ./CMake/Toolchain-Windows-amd64.cmake
    Using toolchain ./CMake/Toolchain-Windows-amd64.cmake in 'Debug' mode
    -- The C compiler identification is unknown
    CMake Error at CMakeLists.txt:8 (project):
      The CMAKE_C_COMPILER:

        x86_64-w64-mingw32-gcc

      is not a full path and was not found in the PATH.

      Tell CMake where to find the compiler by setting either the environment
      variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
      the compiler, or to the compiler name if it is in the PATH.

    -- Configuring incomplete, errors occurred!
    See also "/home/me/bee-host/CMakeFiles/CMakeOutput.log".
    See also "/home/me/bee-host/CMakeFiles/CMakeError.log".
    make: *** No targets specified and no makefile found.  Stop.
    make: *** No rule to make target 'package'.  Stop.
    Processing ./CMake/Toolchain-Windows-i686.cmake
    Using toolchain ./CMake/Toolchain-Windows-i686.cmake in 'Debug' mode
    -- The C compiler identification is unknown
    CMake Error at CMakeLists.txt:8 (project):
      The CMAKE_C_COMPILER:

        i686-w64-mingw32-gcc

      is not a full path and was not found in the PATH.

      Tell CMake where to find the compiler by setting either the environment
      variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
      the compiler, or to the compiler name if it is in the PATH.

    -- Configuring incomplete, errors occurred!
    See also "/home/me/bee-host/CMakeFiles/CMakeOutput.log".
    See also "/home/me/bee-host/CMakeFiles/CMakeError.log".
    make: *** No targets specified and no makefile found.  Stop.
    make: *** No rule to make target 'package'.  Stop.

**Comment by rosmanov** [comment]
`./build.sh` runs all tool chains trying to compile against all the supported architectures and platforms (amd64, i686; Linux, Windows). There is an option for specific tool chain. For example, you can build for Linux amd64 as described [in README. md](https://github.com/rosmanov/bee-host/blob/master/README.md#64-bit-gnulinux-amd64). But, currently, there is no tool chain for arm architecture. I'll try to add it when I have some free time.

Thanks.

**Comment by rosmanov** [comment]
There was an error that affected all tool chains, actually. (Related to external project dependency.) I've fixed it now, but there is no toolchain for ARM architecture yet. You can try the following:

1. Create `CMake/Toolchain-Linux-arm.cmake` file (relative to the project root directory):
```
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER g++)

set(BEECTL_HOST arm-pc-linux-gnu)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
```
2. Run `build.sh` as follows:

```
mkdir -p build && cd build
../build.sh ../CMake/Toolchain-Linux-arm.cmake -b Release

```

**Note, `build.sh` tries to build RPM, DEB, ZIP, and TGZ packages on Linux platform. You might want to either modify the script, or run `cmake` manually, e.g.:**
```
git clone git@github.com:rosmanov/bee-host.git
cd bee-host

mkdir -p build && cd build

cmake -DCMAKE_TOOLCHAIN_FILE="$(realpath .)/../CMake/Toolchain-Linux-arm.cmake" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCPACK_GENERATOR=RPM ..

make
make package
```

The commands above should generate `beectl-1.1.4-1.arm.Release.rpm` package.

**Comment by rosmanov** [comment]
@archenemies , I've added a toolchain configuration for ARM (`CMake/Toolchain-Linux-arm.cmake`) and cross-compiled some packages with it (RPM, DEB, and TGZ): [arm-builds.zip](https://github.com/rosmanov/bee-host/files/3828276/arm-builds.zip)

**Comment by rosmanov** [comment]
If you have troubles with the tool chain or the binaries, please reopen this issue.
