### ISSUE TITLE
Missing Architecture field in the deb

### ISSUE THREAD

**Issue by hanophora** [rosmanov/bee-host#4]
The mandatory 'Architecture' field is not filled in debian/control. This results in a flood of warnings every time I do anything with dpkg (eg installing or upgrading any package):

```
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 2615 package 'beectl':
 missing 'Architecture' field
```

I get this additional warning when installing (which needs `--force-architecture` because of this bug):
```
dpkg: warning: parsing file '/var/lib/dpkg/tmp.ci/control' near line 9 package 'beectl':
 empty value for 'Architecture' field
```

**Comment by rosmanov** [comment]
Fixed. The new packages are available on [SourceForge](https://sourceforge.net/projects/beectl/files/Linux/). You'll likely need one of the following:

- [`beectl-1.3.2-1.i386.Release.deb`](https://sourceforge.net/projects/beectl/files/Linux/beectl-1.3.2-1.i386.Release.deb/download)
- [`beectl-1.3.2-1.amd64.Release.deb`](https://sourceforge.net/projects/beectl/files/Linux/beectl-1.3.2-1.amd64.Release.deb/download) (:point_left: most likely this one)

**Update: I just created a [release](https://github.com/rosmanov/bee-host/releases/tag/1.3.2), so the packages are available there as well.**

**Comment by hanophora** [comment]
Thanks a lot!
