### ISSUE TITLE
Problem with spaces in path under Windows

### ISSUE THREAD

**Issue by AlexanderS** [rosmanov/bee-host#5]
Hi,

when using a path for the editor like this: "C:\Program Files\Vim\vim80\gvim.exe" it does not work. gvim will start, but tries to open "Files\Vim\vim80\gvim.exe". I think the arguments for the commands are not properly escaped in [concat_args](https://github.com/rosmanov/bee-host/blob/master/src/shell.c#L49).

You can use something like this "C:\Progra~1\Vim\vim80\gvim.exe" as workaround, but it would be more convenient if spaces would be supported.

Thanks,
Alex

**Comment by rosmanov** [comment]
Hi,

The issue should be fixed now in version 1.3.3. Tested on Windows 10 x86_64. Should work without explicit double quotes in the extension settings.

Thanks.
